### ISSUE TITLE
语音无法发送

### ISSUE THREAD

**Issue by BearBin1215** [GWYOG/HoshinoBotVoiceGuessPlugin#3]
使用的是cqhttp-mirai插件（cqhttp-mirai-0.1.9-all.jar）
后台这样显示：
```
[2020-11-06 22:47:01,264 voiceguess] ERROR: <ActionFailed, retcode=103>
Traceback (most recent call last):
  File "C:\one-key-xcw\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\one-key-xcw\HoshinoBot\hoshino\modules\voiceguess\voiceguess.py", line 110, in cygames_voice_guess
    await bot.send(ev, MessageSegment.record(f'file:///{os.path.abspath(file_path)}'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 256
, in send
    return await self.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 223
, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 186
, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 161
, in call_action
    return _handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 51,
 in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=103>
[2020-11-06 22:47:01,272 nonebot] INFO: Message 1500 is ignored
```
群内有
`猜猜这个“cygames”语音来自哪位角色? (30s后公布答案)`
但是没有语音发出来，需要转成silk格式吗

**Comment by GWYOG** [comment]
你的cqhttp-mirai插件版本太低了，建议[更新](https://github.com/yyuueexxiinngg/cqhttp-mirai/releases)，更新后问题应该就解决了。
P.S.1 更新到最新版后不需要再转silk格式了，不过m4a语音PC无法收听，只能手机端收听。
P.S.2 我曾经也尝试过在cqhttp-mirai环境下转换成silk，但是由于mirai的[bug](https://github.com/mamoe/mirai/issues/577)，效果很差。如果坚持使用cqhttp-mirai的话，我没想到解决PC端无法收听问题的办法。

如更新到最新版仍无法发送，请Reopen这个issue  ;D
