### ISSUE TITLE
语音无法发送

### ISSUE THREAD

**Issue by PterHang** [GWYOG/HoshinoBotVoiceGuessPlugin#4]
使用的是gocqhttp:0.9.31-fix2，也已经部署了ffmpeg version 3.4.8-0ubuntu0.2
后台显示的是
```[2020-11-24 15:07:47,944 voiceguess] ERROR: <ActionFailed, retcode=100>
Traceback (most recent call last):
  File "/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/HoshinoBot/hoshino/modules/voiceguess/voiceguess.py", line 110, in cygames_voice_guess
    await bot.send(ev, MessageSegment.record(f'file:///{os.path.abspath(file_path)}'))
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 256, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>
```
群内有
猜猜这个“cygames”语音来自哪位角色? (30s后公布答案)但是没有发送语音

**Comment by GWYOG** [comment]
`retcode=100`说明go-cqhttp那儿无法把语音发出去。可能是ffmpeg没部署正确？
建议看一下go-cqhttp后台的提示，那儿应该有更详细的原因说明。

**Comment by PterHang** [comment]
go-cqhttp显示的是这个
```
[2020-11-24` 10:19:08] [INFO]: 收到群 布施民、EL PSY CONGROO(763609785) 内 EL PSY CONGROO(740943125) 的消息: cygames (1052692666) 
[2020-11-24 10:19:08] [INFO]: 发送群 763609785(763609785)  的消息: [{"type":" ... (-1375613653) 
[2020-11-24 10:19:08] [WARNING]: 转换CQ码到MiraiGo Element时出现错误: syntax error 将忽略本段CQ码. 
[2020-11-24 10:19:08] [WARNING]: 群消息发送失败: 消息为空. 
```
ffmpeg应该是没问题的
```
root@iZ2zee2m2pgkny2x0m4s29Z:~# ffmpeg
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

**Comment by GWYOG** [comment]
有点迷..`syntax error`这个提示说明应该不是ffmpeg的问题，而是CQ码格式可能有问题。（可以参见go-cqhttp这个[issue](https://github.com/Mrs4s/go-cqhttp/issues/431)）
不过我不太清楚到底哪儿出了问题。windows系统不会有路径格式问题，理论上linux应该也不会出问题才对

**Comment by PterHang** [comment]
我看了一下，猜头像给答案的时候也出现了路径的问题。
‘ [WARNING]: 转换CQ码到MiraiGo Element时出现错误: open //HoshinoBot/res/img/priconne/unit/icon_unit_109731.png: no such file or directory 将忽略本段CQ码.’
应该是路径的问题

**Comment by GWYOG** [comment]
你试试把HoshinoBot的配置文件中资源文件夹res的路径最前面那个双斜杠改成单斜杠？

**Comment by GWYOG** [comment]
P.S. 想问下你HoshinoBot原本的发图功能你能不能用，比如“谁是黑猫”指令。如果猜头像那儿都出问题的话，我感觉是你资源文件夹路径写错了，因为猜头像发图和HoshinoBot发图的代码基本一样。

**Comment by PterHang** [comment]
能返回名称答案，但是没有图像。应该是路径错了 
`转换CQ码到MiraiGo Element时出现错误: open //HoshinoBot/res/img/priconne/unit/icon_unit_106061.png: no such file or directory 将忽略本段CQ码. `
\_\_bot\_\_.py文件里的 `RES_DIR = r'./res'`

**Comment by GWYOG** [comment]
默认值应该就是这个吧，不清楚为什么不行，实在不行可以改成绝对路径试试。我也是头一次见到你这种情况
P.S. 你那儿有res文件夹和里面的图片文件吧？

**Comment by PterHang** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/root/qqbot/Hoshino/res/img/priconne/unit/icon_unit_106061.png'
[2020-11-24 23:55:55,234 nonebot] INFO: Message 768943400 is ignored
root@iZ2zee2m2pgkny2x0m4s29Z:~/qqbot/Hoshino/hoshino/config# /root/qqbot/Hoshino/res/img/priconne/unit/icon_unit_106061.png
-bash: /root/qqbot/Hoshino/res/img/priconne/unit/icon_unit_106061.png: Permission denied
```
res文件和图片都是在的。我用绝对路径也报no such file。

**Comment by zyujs** [comment]
cd /root/qqbot/
chmod -R 777 *

**Comment by PterHang** [comment]
重启了下docker，发送图片功能都没问题了，路径用默认的就行。但是发送语音功能还是没有
go-cqhttp后台这次显示
```
[2020-11-25 04:02:57] [INFO]: 收到群 小心甜心刀(1016750487) 内 喵呜(740943125) 的消息: cygames (1744693036) 
[2020-11-25 04:02:58] [INFO]: 发送群 1016750487(1016750487)  的消息: [{"type":" ... (284874682) 
[2020-11-25 04:02:58] [WARNING]: 转换CQ码到MiraiGo Element时出现错误: exit status 127 将忽略本段CQ码
```
所以这应该是ffmpeg没正确部署嘛

**Comment by GWYOG** [comment]
我也不是很清楚，你加下HoshinoBot QQ交流群367501912吧，GitHub上交流太不方便了
